const actions = {
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  INCREASE_PRODUCT_COUNT: 'INCREASE_PRODUCT_COUNT',
  DECREASE_PRODUCT_COUNT: 'DECREASE_PRODUCT_COUNT',
};

export default actions;
